services:
  nginx:
    build:
      context: ./.docker/nginx
    depends_on:
      - php
    ports:
      - '8034:80'
    volumes:
      - ./:/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: .docker/php
    volumes:
      - ./:/app
    expose:
      - 9000
    links:
      - mysql
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: 'serverName=docker'

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - '3386:3306'
    expose:
      - '3306'
    volumes:
      - ./.data/db:/var/lib/mysql:rw
      - ./.docker/db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
